[build]
  command = "npm run build"
  publish = "."  # Replace with the directory where your static assets are generated

[dev]
  command = "npm start"

[context.production.environment]
  NODE_ENV = "production"
